### ISSUE TITLE
Error: No mailbox selected 

### ISSUE THREAD

**Issue by danhawkes** [cfe84/screenr#1]
Hi, I get an error when running with the template config (imap credentials redacted):

```json
{
  "folders": {
    "Inbox": {
      "folder": "INBOX",
      "screeningFolder": "INBOX.Screened"
    },
    "ForScreening": "INBOX.ForScreening",
    "Newsletter": "INBOX.Newsletter",
    "Reference": "INBOX.Reference",
    "Rejected": "INBOX.Rejected"
  },
  "storageFolder": "./",
  "pollFrequencySeconds": 5
}
```

```
Started screening
Opened connection
Error: No mailbox selected (0.001 + 0.000 secs).
    at Object.callback (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:286:25)
    at Imap._handleResponse (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:664:28)
    at Imap._parseIncomingCommands (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:624:12)
    at Imap._onData (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:434:10)
    at TCPSocket.socket.ondata (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:153:16)
    at TCPSocket._emit (/usr/src/app/node_modules/emailjs-tcp-socket/dist/node-socket.js:103:31)
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/emailjs-tcp-socket/dist/node-socket.js:69:23)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
```

**Comment by cfe84** [comment]
The error is disgusting but the most likely explanation is that one of the folders in your config file doesn't exist.

**Comment by danhawkes** [comment]
I'm not sure if I've understood the configuration but I've created folders matching the above and am still seeing the same error:

![image](https://user-images.githubusercontent.com/3388897/87453578-94f80700-c5fa-11ea-8697-9b293db1b854.png)
![image](https://user-images.githubusercontent.com/3388897/87453770-eef8cc80-c5fa-11ea-92c8-5dc8a9865fa0.png)

**Comment by cfe84** [comment]
I'll add a better error messages, and maybe list the existing folders on connection. In the mean time there are multiple things you might want to try:

1. Try with `INBOX/` instead of `INBOX.`
2. Try without the `INBOX` at all (looks like Gmail doesn't prefix for example)
3. Folder names are usually case sensitive, you can check if replacing with `Inbox.` does anything.

**Comment by danhawkes** [comment]
Thanks! It worked to replace the dot delimiters with slashes:
```json
"ForScreening": "INBOX/ForScreening"
```
Reading the [spec](https://tools.ietf.org/html/rfc3501#section-5.1.1) it seems the delimiter character is undefined, so probably depends on your email provider:

> 5.1.1.  Mailbox Hierarchy Naming
>
> If it is desired to export hierarchical mailbox names, mailbox names
   MUST be left-to-right hierarchical using a single character to
   separate levels of hierarchy.  The same hierarchy separator character
   is used for all levels of hierarchy within a single name.
