### ISSUE TITLE
Error: UID FETCH not allowed now.

### ISSUE THREAD

**Issue by lcarrasco** [cfe84/screenr#2]
Hi, I am trying to make it work with my GSuite email account. I have enabled IMAP access in my account and created an app password, also I've configured it in Apple Mail with those settings just to be sure.

However when I start the container the following error appears:

```
Started screening
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Opened connection
Error: UID FETCH not allowed now.
    at Object.callback (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:286:25)
    at Imap._handleResponse (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:664:28)
    at Imap._parseIncomingCommands (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:624:12)
    at Imap._onData (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:434:10)
    at TCPSocket.socket.ondata (/usr/src/app/node_modules/emailjs-imap-client/dist/imap.js:153:16)
    at TCPSocket._emit (/usr/src/app/node_modules/emailjs-tcp-socket/dist/node-socket.js:103:31)
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/emailjs-tcp-socket/dist/node-socket.js:69:23)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
```

My template is:

```json
{
  "imap": {
    "host": "imap.gmail.com",
    "port": 993,
    "user": "***@gsuitedomain.com",
    "password": "[REDACTED]"
  },
  "folders": {
    "Inbox": {
      "folder": "[Gmail]/Inbox",
      "screeningFolder": "[Gmail]/Screened"
    },
    "ForScreening": "[Gmail]/ForScreening",
    "Newsletter": "[Gmail]/The Feed",
    "Reference": "[Gmail]/Papertrail",
    "Rejected": "[Gmail]/Rejected"
  },
  "storageFolder": "./",
  "pollFrequencySeconds": 5
}
``

Any help would be appreciated. 

Thanks

**Comment by lcarrasco** [comment]
Nevermind, I found out after enabling logging that my settings where wrong. In case it helps someone, the config.json for a GSuite account is the following:

```json
{
  "imap": {
    "host": "imap.gmail.com",
    "port": 993,
    "user": "your@gsuitedomain.com",
    "password": "**********"
  },
  "folders": {
    "Inbox": {
      "folder": "INBOX",
      "screeningFolder": "Screened"
    },
    "ForScreening": "ForScreening",
    "Newsletter": "The Feed",
    "Reference": "Paper Trail",
    "Rejected": "Rejected"
  },
  "storageFolder": "./",
  "pollFrequencySeconds": 5
}
```

**Comment by cfe84** [comment]
Thanks, error message is a bit disgusting, I'll see if I can make it better for the next folk
